# EU: в одном POD-контейнеры: имеет смысл поднимать дополнительно свой cache(reddis), или связанные-неразрывно-apps (monitoring, auth or anticorruption-app) that scales together.

apiVersion: apps/v1 #eu: other apiVersion for 'Deployment'!!!!! not v1 (cubectl or UI only calls the API..)
kind: Deployment
metadata:
  name: hotel-server
  labels:
    app: hotel-server
spec:
  replicas: 1 #achtung, how much instances for "LoadBalancer"
  template:
    metadata:
      name: hotel-server
      labels:
        app: hotel-server #app name
    spec:
      containers: #eu: list, but here only one container from image!!
        - name: hotel-server
          image: eugenfff/hotel-server:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 #eu: others have to send to this port (only  for documentation)! But pod can listen not only this port. 
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube #//application-KUBE.properties will be seleced
      restartPolicy: Always
  selector:
    matchLabels:
      app: hotel-server
