CREATE DATABASE hotel;
CREATE USER eu_user WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE hotel TO eu_user;

-- \connect hotel;
-- CREATE SCHEMA IF NOT EXISTS hotel AUTHORIZATION eu_user;
-- CREATE SCHEMA IF NOT EXISTS customer AUTHORIZATION eu_user;