image:
  hotelApp: eugenfff/hotel-app:latest
  gateway: eugenfff/gateway:latest
  keycloak: quay.io/keycloak/keycloak:24.0
  postgres: postgres:16
  kafka: bitnami/kafka:latest

keycloak:
  hostname: keycloak.local
  realm: hotel-socialoffers
  admin:
    user: admin
    password: admin
  db:
    user: keycloak
    password: keycloak
    name: keycloak

postgres:
  db:
    user: hotel
    password: hotel
    name: hotelico

kafka:
  zookeeperImage: bitnami/zookeeper:3.8
  replicas: 1

gateway:
#  image: eugenfff/gateway:latest
  port: 8080

services:
  - name: chat
    image: eugenfff/hotel-chat:latest
    port: 8081
  - name: booking
    image: eugenfff/hotel-booking:latest
    port: 8082
  - name: menu
    image: eugenfff/hotel-menu:latest
    port: 8083