server:
  port: 8082
spring:
  application:
    name: messaging
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/messaging
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#its my own optionFlag, for @Values in @Config class :)
rabbitmq:
  exchanges: #names of rabbitmq exchanges. Topic exchange?
    internal: internal.exchange #default direct exchange of rabbit? 
  queue: #which queues do we use?
    notification: notification.queue #only one: notification queue
  routing-keys: #binding rule to a queue? we have only notification-queue
    internal-notification: internal.notification.routing-key #its a binding-rule to 'notification' queue
    
    