spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411 # container_name: zipkin-server in docker.compose
  cloud:
    gateway:
      routes: 
        - id: hotel
          uri: lb://HOTEL
          predicates:
            - Path=/api/v1/hotels/**        
        - id: menu
          uri: lb://MENU
          predicates:
            - Path=/api/v1/menus/**        
        - id: chat
          uri: lb://CHAT
          predicates:
            - Path=/api/v1/chat/**
server:
  port: 8083
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # container_name: eureka-server in docker.compose
                  # connecting containers on common docker network='spring'
    fetch-registry: true
    register-with-eureka: true