spring:
  application:
    name: hotel-app
  profiles:
    active: development
  config:
    import: optional:classpath:application-${spring.profiles.active}.yml
#  config.activate.on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5434/hotel
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create #eugen, not for production: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    
#    generate-ddl: true
#    defer-datasource-initialization: true 
  #  zipkin:
#    base-url: http://localhost:9411

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  http: #http: boot1 | #servlet: boot2
    multipart:
      location: ${java.io.tmpdir}
      max-file-size: 512MB # Max file size.
      max-request-size: 512MB # Max request size.
  messages.basename: i18n/messages # Configure MessageSource to lookup any validation/error message in internationalized property files
  kafka:
    enabled: false
    bootstrap-servers: localhost:19092
    listener:
      auto-startup: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: hotelico-group
      properties:
        spring.json.trusted.packages: eu.getsoftware.hotelico.*
        spring.json.value.default.type: eu.getsoftware.hotelico.clients.api.application.infrastructure.domainevents.domainmessage.DomainMessage

  social:
    facebook:
      appId: 383626641847356
      appSecret: f492cdd7e0d9aee36ce8446c5caa440d
    linkedIn:
      clientId: 77rxbh8n0ta2fc
      clientSecret: aW3L9r9racGYIV5I
  cache:
    cache-names: userCache, propertyCache
    caffeine:
      spec: maximumSize=500, expireAfterAccess=300s
  mail:
    host: smtp.gmail.com #smtp.strato.de
    port: 587
    username: eugen.wi83@gmail.com #sergej.neustadt@hotelico.de
    password: FaRsHuLeGe
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  main: #eugen kastil, delete it
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver: 
        jwt:
          issuer-uri: http://keycloak:8089/realms/hotel-socialoffers
          #использовать 'keycloak' (а не 'localhost') как hostname — потому что это внутренняя сеть Docker Compose.
          #issuer-uri заменяет необходимость в KeycloakConfigResolver.
      client:
        registration: 
          keycloak:
            client-id: hotel-app
            client-secret: UtKfssqVcaAnCcgNNULWS1fAPCjtpjMx
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak
        provider:  
          keycloak:
            issuer-uri: http://localhost:8089/realms/hotel-socialoffers #Realm = hotel-socialoffers
            user-name-attribute: preferred_username

#entitymanager:
#  packagesToScan: de.getsoftware.smsbridge.model      
security:
  basic.enabled: false #eugen: not in spring boot 2.x  

#hotelico:
#  security:
#    keycloak:
#      enabled: false
#      issuer-uri: http://localhost:8089/realms/hotel-socialoffers
    
#liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml #boot2: liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: 8088
  error:
    whitelabel.enabled: false
    
#keycloak:
#  auth-server-url: http://localhost:8080
#  realm: hotel-socialoffers
#  resource: hotel-app
#  credentials:
#    secret: YOUR_CLIENT_SECRET
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka      
---

spring:
  config.activate.on-profile: development
#  datasource:
#    url: jdbc:postgresql://localhost:5434/hotel
#    username: postgres #//eu_user with own roles
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: create #eugen, not for production: update
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework:
      security: INFO
      boot.actuate.audit.listener.AuditListener: DEBUG
    org.hibernate.type: TRACE
#    org.hibernate: #eu: test jpa
#      orm: DEBUG
#      SQL: DEBUG
  
#keycloak:
#  enabled: false
#  #config.file: classpath:static/backend-keycloak.json
#  realm: EugenRealm
#  auth_server_url: http://keycloakintern.getSoftware.eu:8080/auth
#  #credentials.secret: 5251920c-edb0-4d51-8ddb-48cb9a0136b4

server:
  port: 8088

---

spring:
  config:
    activate:
      on-profile: testing
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: postgres
keycloak:
  enabled: false
  #config.file: classpath:static/backend-keycloak.json
  realm: GetSoftware
  auth_server_url: http://keycloakintern.getSoftware.eu:8080/auth
  #credentials.secret: 5251920c-edb0-4d51-8ddb-48cb9a0136b4

server:
  port: 8084

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: #EXTERNALIZED
    username: hotelico
    password: frankfurt_2015

keycloak:
  enabled: false
  #config.file: classpath:static/backend-keycloak.json
  realm: GetSoftware
  auth_server_url:
  #credentials.secret: 5251920c-edb0-4d51-8ddb-48cb9a0136b4

server:
  port: 8080
  
        
#jdbc.driverClassName = com.mysql.jdbc.Driver
#jdbc.url = jdbc:mysql://localhost:3306/hotel
#jdbc.username = root
#hibernate.dialect = org.hibernate.dialect.MySQLDialect
#hibernate.show_sql = false
#hibernate.format_sql = false

