spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://hotel-zipkin:9411
    
server:
  port: 8761
  
eureka: ##its only a server, no client registration here
  client:
    fetch-registry: false
    register-with-eureka: false
    
    